### ISSUE TITLE
It is necessary to build numpyx to be compatible with numpy 2

### ISSUE THREAD

**Issue by charlesneimog** [gesellkammer/numpyx#1]
Hi, it is necessary to rebuild numpyx to be compatible with numpy 2.0 or higher. 

Thanks!

EDIT: I had no problems on Linux, build `python setup.py build` solves the problem.

**Comment by gesellkammer** [comment]
The latest version (1.4) requires numpy >= 2 and the wheels are built with that requirement. All tests seem to be passing

**Comment by charlesneimog** [comment]
thanks
